app:
  addrbook_path: '$HOME'
  addrbook_filename: '.omg.json'
  alias_length: 3

chain:
  daemon: 'onomyd'
  chain_id: 'onomy-testnet-1'
  address_prefix: 'onomy'
  valoper_prefix: 'onomyvaloper'
  base_denom: 'anom'
  token: 'NOM'
  decimals: 18

options:
  default_fee: '1212anom'
  gas_adjust: 1.2
  keyring_backend: 'test'
  remainder: '1000000000000anom'